var json = [
  {
    "Inventory Number":"G-NES00164",
    "Lot Number":171708944076,
    "Title":"Dungeon Magic: Sword of the Elements",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"Working",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00171",
    "Lot Number":171708944076,
    "Title":"Platoon",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00172",
    "Lot Number":171708944076,
    "Title":"Rambo",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00175",
    "Lot Number":171708944076,
    "Title":"Legacy of the Wizard",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00179",
    "Lot Number":171708944076,
    "Title":"Wizardry: Proving Grounds of the Mad Overlord",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"Unknown",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"I don't know if the battery is working, and I don't have a clue how to get to a save or load screen. This game doesn't seem fun in the slightest. Do you like menus? Then buy this game for some intense menu action!",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00180",
    "Lot Number":171708944076,
    "Title":"Deadly Towers",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00182",
    "Lot Number":171708944076,
    "Title":"Teenage Mutant Ninja Turtles",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00183",
    "Lot Number":171708944076,
    "Title":"Teenage Mutant Ninja Turtles II: The Arcade Game",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00189",
    "Lot Number":171708944076,
    "Title":"Mystery Quest",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00190",
    "Lot Number":171708944076,
    "Title":"Zoda's Revenge: StarTropics II",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"Working",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Very Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00198",
    "Lot Number":171708944076,
    "Title":"Low G Man: The Low Gravity Man",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00211",
    "Lot Number":171708944076,
    "Title":"Rocket Ranger",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Very Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00227",
    "Lot Number":171708944076,
    "Title":"Phantom Fighter",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00229",
    "Lot Number":171708944076,
    "Title":"Castlequest",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Very Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00233",
    "Lot Number":171708944076,
    "Title":"P.O.W.: Prisoners of War",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00235",
    "Lot Number":171708944076,
    "Title":"Ikari Warriors II: Victory Road",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00238",
    "Lot Number":171708944076,
    "Title":"Section-Z",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00239",
    "Lot Number":171708944076,
    "Title":"Jackal",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00243",
    "Lot Number":171708944076,
    "Title":"Wizards & Warriors",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00246",
    "Lot Number":171708944076,
    "Title":"Time Lord",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00247",
    "Lot Number":171708944076,
    "Title":"Karnov",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00249",
    "Lot Number":171708944076,
    "Title":"Code Name: Viper",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00258",
    "Lot Number":171708944076,
    "Title":"Double Dragon III: The Sacred Stones",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00259",
    "Lot Number":171708944076,
    "Title":"Ikari III: The Rescue",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00260",
    "Lot Number":171708944076,
    "Title":"Dragon Power",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00266",
    "Lot Number":171708944076,
    "Title":"RoboCop",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Fair",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00270",
    "Lot Number":171708944076,
    "Title":"Golgo 13: Top Secret Episode",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00271",
    "Lot Number":171708944076,
    "Title":"Mafat Conspiracy, The",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00272",
    "Lot Number":171708944076,
    "Title":"Adventures of Lolo",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"Good",
    "Manual Condition Details":"Manual has slight corner creasing.",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00273",
    "Lot Number":171708944076,
    "Title":"Ninja Gaiden II: The Dark Sword of Chaos",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00277",
    "Lot Number":171708944076,
    "Title":"King's Knight",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00282",
    "Lot Number":171708944076,
    "Title":"Milon's Secret Castle",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00368",
    "Lot Number":221738212031,
    "Title":"Astyanax",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Fair",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00373",
    "Lot Number":221738212031,
    "Title":"Blaster Master",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00380",
    "Lot Number":221738212031,
    "Title":"Code Name: Viper",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00389",
    "Lot Number":221738212031,
    "Title":"Ghosts n' Goblins",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00396",
    "Lot Number":221738212031,
    "Title":"Kid Icarus",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00397",
    "Lot Number":221738212031,
    "Title":"Kirby's Adventure",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00398",
    "Lot Number":221738212031,
    "Title":"Legacy of the Wizard",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Poor",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00399",
    "Lot Number":221738212031,
    "Title":"Life Force",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"Label was slightly misaligned at factory.",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00400",
    "Lot Number":221738212031,
    "Title":"Little Nemo: The Dream Master",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"Front label has some tape at bottom.",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00408",
    "Lot Number":221738212031,
    "Title":"Metroid (original -- silver label)",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00413",
    "Lot Number":221738212031,
    "Title":"Ninja Gaiden",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00414",
    "Lot Number":221738212031,
    "Title":"Ninja Gaiden II: The Dark Sword of Chaos",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00416",
    "Lot Number":221738212031,
    "Title":"Chip 'n Dale: Rescue Rangers",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00420",
    "Lot Number":221738212031,
    "Title":"Section-Z",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00421",
    "Lot Number":221738212031,
    "Title":"StarTropics",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00430",
    "Lot Number":221738212031,
    "Title":"Teenage Mutant Ninja Turtles III The Manhattan Project",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00472",
    "Lot Number":251920152778,
    "Title":"Kabuki Quantum Fighter",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00490",
    "Lot Number":null,
    "Title":"Battle of Olympus, The",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00585",
    "Lot Number":261895488798,
    "Title":"Incredible Crash Test Dummies",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00618",
    "Lot Number":111681270333,
    "Title":"Race America",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00629",
    "Lot Number":151696762747,
    "Title":"Mike Tyson's Punch Out!!!",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00650",
    "Lot Number":251964573488,
    "Title":"Punch Out",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00677",
    "Lot Number":181770652230,
    "Title":"Mario Bros.",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00685",
    "Lot Number":181770652230,
    "Title":"Tiny Toon Adventures",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00700",
    "Lot Number":181770652230,
    "Title":"Batman",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00798",
    "Lot Number":281725177295,
    "Title":"Pro Wrestling",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Fair",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00800",
    "Lot Number":281725177295,
    "Title":"Paperboy 2",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00802",
    "Lot Number":281725177295,
    "Title":"Legend of Zelda, The (gray)",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"Working",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00803",
    "Lot Number":281725177295,
    "Title":"Kung Fu",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Fair",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00808",
    "Lot Number":281725177295,
    "Title":"Tecmo Bowl",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00813",
    "Lot Number":281725177295,
    "Title":"Robin Hood: Prince of Thieves",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"No",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00815",
    "Lot Number":281725177295,
    "Title":"Goonies II, The",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  },
  {
    "Inventory Number":"G-NES00817",
    "Lot Number":281725177295,
    "Title":"Ivan 'Ironman' Stewart's Super Off Road",
    "Sleeve":"img/megaman.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""
  }
];

var markup = "";
for (var i = 0; i<json.length ;i++) {
                    // <div class="col-sm-4 col-lg-4 col-md-4">
markup += "<div class='col-sm-4 col-lg-4 col-md-4 product' data-name='" + json[i].Title +"' >"; //data-name'whatevergoeshere'
                    //     <div class="thumbnail">
markup += "<div class='thumbnail'>"
                   //      <img src="http://placehold.it/320x150" alt="">
markup += "<img src='"+ json[i].Sleeve + "'>"
markup+="</div> "
                    //         <div class="caption">
markup += "<div class='caption'>"
                    //             <h4 class="pull-right">$24.99</h4>
                    //             <h4><a href="#">First Product</a>
markup += "<h4><a href='#'>" + json[i].Title +" </a></h4></div></div>"
                    //             </h4>
                    //             <p>See more snippets like this online store item at <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>                  
                    //         </div>
                    //         <div class="ratings">
                    //             <p class="pull-right">15 reviews</p>
                    //             <p>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //                 <span class="glyphicon glyphicon-star"></span>
//markup += "<div class=''>"  
                    //             </p>
                    //         </div>
                    //     </div>
                    // </div>
}
$('.products').append(markup);
// console.log(markup);                    