                   

                    // <div class="col-sm-4 col-lg-4 col-md-4">
                    //     <div class="thumbnail">
                    //         <img src="http://placehold.it/320x150" alt="">
                    //         <div class="caption">
                    //             <h4 class="pull-right">$24.99</h4>
                    //             <h4><a href="#">First Product</a>
                    //             </h4>
                    //             <p>See more snippets like this online store item at <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
                    //         </div>
                    //         <div class="ratings">
                    //             <p class="pull-right">15 reviews</p>
                    //             <p>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //             </p>
                    //         </div>
                    //     </div>
                    // </div>

var json = [
  // {
  //   "InventoryNum":"Inventory Number",
  //   "LotNum":"Lot Number",
  //   "FIELD3":"Title",
  //   "FIELD4":"Title Verification",
  //   "FIELD5":"Status",
  //   "FIELD6":"Sleeve",
  //   "FIELD7":"Pins Cleaned",
  //   "FIELD8":"Working",
  //   "FIELD9":"Battery",
  //   "FIELD10":"Cleaned",
  //   "FIELD11":"Front Label",
  //   "FIELD12":"Rear Label",
  //   "FIELD13":"Cart Plastic",
  //   "FIELD14":"Cart Condition Details / Misc Game Details",
  //   "FIELD15":"Box Condition",
  //   "FIELD16":"Box Condition Details",
  //   "FIELD17":"Manual Condition",
  //   "FIELD18":"Manual Condition Details",
  //   "FIELD19":"Map / Poster Condition",
  //   "FIELD20":"Map Condition Details",
  //   "FIELD21":"Insert Condition",
  //   "FIELD22":"Warranty Card"
  // },
  {
    "InventoryNum":"G-NES00163",
    "LotNum":"171708944076",
    "FIELD3":"Legend of Zelda, The (gold)",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"Nintendo",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Very Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00164",
    "LotNum":"171708944076",
    "FIELD3":"Dungeon Magic: Sword of the Elements",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Very Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00165",
    "LotNum":"171708944076",
    "FIELD3":"Final Fantasy",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"Nintendo",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Fair",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00166",
    "LotNum":"171708944076",
    "FIELD3":"Tombs & Treasure",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Fair",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00167",
    "LotNum":"171708944076",
    "FIELD3":"Star Soldier",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Fair",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00168",
    "LotNum":"171708944076",
    "FIELD3":"Metal Storm",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"Nintendo",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00169",
    "LotNum":"171708944076",
    "FIELD3":"Strider",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00170",
    "LotNum":"171708944076",
    "FIELD3":"Metroid (original -- silver label)",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"Nintendo",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00171",
    "LotNum":"171708944076",
    "FIELD3":"Platoon",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00172",
    "LotNum":"171708944076",
    "FIELD3":"Rambo",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00173",
    "LotNum":"171708944076",
    "FIELD3":"Bad Street Brawler",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00174",
    "LotNum":"171708944076",
    "FIELD3":"Dr. Chaos",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00175",
    "LotNum":"171708944076",
    "FIELD3":"Legacy of the Wizard",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Fair",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00176",
    "LotNum":"171708944076",
    "FIELD3":"Dragon Warrior",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Poor",
    "FIELD13":"Poor",
    "FIELD14":"Cart is missing one screw.",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00177",
    "LotNum":"171708944076",
    "FIELD3":"Gauntlet (licensed grey cart)",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00178",
    "LotNum":"171708944076",
    "FIELD3":"Shadowgate ",
    "FIELD4":"Name ERROR",
    "FIELD5":"Received",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00179",
    "LotNum":"171708944076",
    "FIELD3":"Wizardry: Proving Grounds of the Mad Overlord",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Unknown",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Fair",
    "FIELD13":"Good",
    "FIELD14":"I don't know if the battery is working, and I don't have a clue how to get to a save or load screen. This game doesn't seem fun in the slightest. Do you like menus? Then buy this game for some intense menu action!",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00180",
    "LotNum":"171708944076",
    "FIELD3":"Deadly Towers",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Very Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00181",
    "LotNum":"171708944076",
    "FIELD3":"Willow",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Fair",
    "FIELD12":"Good",
    "FIELD13":"Fair",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00182",
    "LotNum":"171708944076",
    "FIELD3":"Teenage Mutant Ninja Turtles",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00183",
    "LotNum":"171708944076",
    "FIELD3":"Teenage Mutant Ninja Turtles II: The Arcade Game",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Fair",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00184",
    "LotNum":"171708944076",
    "FIELD3":"Teenage Mutant Ninja Turtles III The Manhattan Project",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00185",
    "LotNum":"171708944076",
    "FIELD3":"Castlevania II: Simon's Quest",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Fair",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00186",
    "LotNum":"171708944076",
    "FIELD3":"Mega Man",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Fair",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00187",
    "LotNum":"171708944076",
    "FIELD3":"Fester's Quest",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00188",
    "LotNum":"171708944076",
    "FIELD3":"Legendary Wings",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00189",
    "LotNum":"171708944076",
    "FIELD3":"Mystery Quest",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00190",
    "LotNum":"171708944076",
    "FIELD3":"Zoda's Revenge: StarTropics II",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Very Good",
    "FIELD12":"Very Good",
    "FIELD13":"Very Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00191",
    "LotNum":"171708944076",
    "FIELD3":"Swords and Serpents",
    "FIELD4":"Name OK",
    "FIELD5":"Ready to List",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00192",
    "LotNum":"171708944076",
    "FIELD3":"Street Fighter 2010: The Final Fight",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00193",
    "LotNum":"171708944076",
    "FIELD3":"Advanced Dungeons & Dragons: Heroes of the Lance",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00194",
    "LotNum":"171708944076",
    "FIELD3":"Ninja Gaiden",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00195",
    "LotNum":"171708944076",
    "FIELD3":"Mega Man 3",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00196",
    "LotNum":"171708944076",
    "FIELD3":"Guardian Legend, The",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Fair",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00197",
    "LotNum":"171708944076",
    "FIELD3":"Solstice: The Quest for the Staff of Demnos",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00198",
    "LotNum":"171708944076",
    "FIELD3":"Low G Man: The Low Gravity Man",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Fair",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00199",
    "LotNum":"171708944076",
    "FIELD3":"Ghosts 'n Goblins",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00200",
    "LotNum":"171708944076",
    "FIELD3":"Magic of Scheherazade, The",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Very Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00201",
    "LotNum":"171708944076",
    "FIELD3":"Raid on Bungeling Bay",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00202",
    "LotNum":"171708944076",
    "FIELD3":"Hydlide",
    "FIELD4":"Name OK",
    "FIELD5":"Problem",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"No",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Poor",
    "FIELD12":"Poor",
    "FIELD13":"Poor",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00203",
    "LotNum":"171708944076",
    "FIELD3":"Castle of Dragon",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00204",
    "LotNum":"171708944076",
    "FIELD3":"Defender of the Crown",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Fair",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00205",
    "LotNum":"171708944076",
    "FIELD3":"Ikari Warriors",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Fair",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00206",
    "LotNum":"171708944076",
    "FIELD3":"Xexyz",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00207",
    "LotNum":"171708944076",
    "FIELD3":"8 Eyes",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00208",
    "LotNum":"171708944076",
    "FIELD3":"Solomon's Key",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00209",
    "LotNum":"171708944076",
    "FIELD3":"Castlevania",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Fair",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00210",
    "LotNum":"171708944076",
    "FIELD3":"Airwolf",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00211",
    "LotNum":"171708944076",
    "FIELD3":"Rocket Ranger",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Very Good",
    "FIELD12":"Very Good",
    "FIELD13":"Very Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00212",
    "LotNum":"171708944076",
    "FIELD3":"Robo Warrior",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00213",
    "LotNum":"171708944076",
    "FIELD3":"Blaster Master",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00214",
    "LotNum":"171708944076",
    "FIELD3":"Friday the 13th",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00215",
    "LotNum":"171708944076",
    "FIELD3":"Predator",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00216",
    "LotNum":"171708944076",
    "FIELD3":"Magician",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00217",
    "LotNum":"171708944076",
    "FIELD3":"Super Pitfall",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00218",
    "LotNum":"171708944076",
    "FIELD3":"Commando",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Fair",
    "FIELD12":"Fair",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00219",
    "LotNum":"171708944076",
    "FIELD3":"Clash at Demonhead",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00220",
    "LotNum":"171708944076",
    "FIELD3":"Ironsword: Wizards & Warriors II",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Fair",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00221",
    "LotNum":"171708944076",
    "FIELD3":"Indiana Jones and the Last Crusade (Taito)",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00222",
    "LotNum":"171708944076",
    "FIELD3":"Double Dragon II: The Revenge",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00223",
    "LotNum":"171708944076",
    "FIELD3":"Adventures of Bayou Billy, The",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00224",
    "LotNum":"171708944076",
    "FIELD3":"Goonies II, The",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00225",
    "LotNum":"171708944076",
    "FIELD3":"Twin Cobra",
    "FIELD4":"Name OK",
    "FIELD5":"Ready to List",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00226",
    "LotNum":"171708944076",
    "FIELD3":"Mendel Palace",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Very Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00227",
    "LotNum":"171708944076",
    "FIELD3":"Phantom Fighter",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00228",
    "LotNum":"171708944076",
    "FIELD3":"Uninvited",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Very Good",
    "FIELD12":"Very Good",
    "FIELD13":"Very Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00229",
    "LotNum":"171708944076",
    "FIELD3":"Castlequest",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Very Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00230",
    "LotNum":"171708944076",
    "FIELD3":"Mega Man 4",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00231",
    "LotNum":"171708944076",
    "FIELD3":"Sky Shark",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"No",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Very Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00232",
    "LotNum":"171708944076",
    "FIELD3":"Ultima: Exodus",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Fair",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00233",
    "LotNum":"171708944076",
    "FIELD3":"P.O.W.: Prisoners of War",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00234",
    "LotNum":"171708944076",
    "FIELD3":"3-D WorldRunner",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00235",
    "LotNum":"171708944076",
    "FIELD3":"Ikari Warriors II: Victory Road",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00236",
    "LotNum":"171708944076",
    "FIELD3":"Indiana Jones and the Temple of Doom (Mindscape)",
    "FIELD4":"Name OK",
    "FIELD5":"Ready to List",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00237",
    "LotNum":"171708944076",
    "FIELD3":"Back to the Future",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00238",
    "LotNum":"171708944076",
    "FIELD3":"Section-Z",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00239",
    "LotNum":"171708944076",
    "FIELD3":"Jackal",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00240",
    "LotNum":"171708944076",
    "FIELD3":"Double Dragon",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00241",
    "LotNum":"171708944076",
    "FIELD3":"Dragon Warrior II",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Fair",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00242",
    "LotNum":"171708944076",
    "FIELD3":"Magmax",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00243",
    "LotNum":"171708944076",
    "FIELD3":"Wizards & Warriors",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00244",
    "LotNum":"171708944076",
    "FIELD3":"Zelda II: The Adventure of Link (gold)",
    "FIELD4":"Name OK",
    "FIELD5":"Received",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Fair",
    "FIELD12":"Fair",
    "FIELD13":"Fair",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00245",
    "LotNum":"171708944076",
    "FIELD3":"Who Framed Roger Rabbit",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Fair",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00246",
    "LotNum":"171708944076",
    "FIELD3":"Time Lord",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00247",
    "LotNum":"171708944076",
    "FIELD3":"Karnov",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00248",
    "LotNum":"171708944076",
    "FIELD3":"Super Mario Bros. 2",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"Nintendo",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00249",
    "LotNum":"171708944076",
    "FIELD3":"Code Name: Viper",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00250",
    "LotNum":"171708944076",
    "FIELD3":"Conquest of the Crystal Palace",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00251",
    "LotNum":"171708944076",
    "FIELD3":"Top Gun: The Second Mission",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00252",
    "LotNum":"171708944076",
    "FIELD3":"Destiny of an Emperor",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00253",
    "LotNum":"171708944076",
    "FIELD3":"Rygar ",
    "FIELD4":"Name ERROR",
    "FIELD5":"Ready to List",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00254",
    "LotNum":"171708944076",
    "FIELD3":"Dragon Warrior III",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Fair",
    "FIELD12":"Good",
    "FIELD13":"Fair",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00255",
    "LotNum":"171708944076",
    "FIELD3":"Crystalis",
    "FIELD4":"Name OK",
    "FIELD5":"Problem",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Unknown",
    "FIELD10":"Yes",
    "FIELD11":"Fair",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00256",
    "LotNum":"171708944076",
    "FIELD3":"StarTropics",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00257",
    "LotNum":"171708944076",
    "FIELD3":"Iron Tank",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00258",
    "LotNum":"171708944076",
    "FIELD3":"Double Dragon III: The Sacred Stones",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Fair",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00259",
    "LotNum":"171708944076",
    "FIELD3":"Ikari III: The Rescue",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Very Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00260",
    "LotNum":"171708944076",
    "FIELD3":"Dragon Power",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00261",
    "LotNum":"171708944076",
    "FIELD3":"Operation Wolf",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00262",
    "LotNum":"171708944076",
    "FIELD3":"DuckTales",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00263",
    "LotNum":"171708944076",
    "FIELD3":"Silent Service",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00264",
    "LotNum":"171708944076",
    "FIELD3":"Digger T. Rock: The Legend of the Lost City",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00265",
    "LotNum":"171708944076",
    "FIELD3":"Castlevania III: Dracula's Curse",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00266",
    "LotNum":"171708944076",
    "FIELD3":"RoboCop",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Fair",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00267",
    "LotNum":"171708944076",
    "FIELD3":"Dr. Jekyll and Mr. Hyde",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00268",
    "LotNum":"171708944076",
    "FIELD3":"Cobra Command",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Fair",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00269",
    "LotNum":"171708944076",
    "FIELD3":"Kid Icarus",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00270",
    "LotNum":"171708944076",
    "FIELD3":"Golgo 13: Top Secret Episode",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Very Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00271",
    "LotNum":"171708944076",
    "FIELD3":"Mafat Conspiracy, The",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00272",
    "LotNum":"171708944076",
    "FIELD3":"Adventures of Lolo",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"Good",
    "FIELD18":"Manual has slight corner creasing.",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00273",
    "LotNum":"171708944076",
    "FIELD3":"Ninja Gaiden II: The Dark Sword of Chaos",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00274",
    "LotNum":"171708944076",
    "FIELD3":"Fist of the North Star",
    "FIELD4":"Name OK",
    "FIELD5":"Ready to List",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00275",
    "LotNum":"171708944076",
    "FIELD3":"G.I. Joe: A Real American Hero",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00276",
    "LotNum":"171708944076",
    "FIELD3":"Uncharted Waters",
    "FIELD4":"Name OK",
    "FIELD5":"Sold",
    "FIELD6":"Blank",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00277",
    "LotNum":"171708944076",
    "FIELD3":"King's Knight",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00278",
    "LotNum":"171708944076",
    "FIELD3":"Ultima: Exodus",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Not Working",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00279",
    "LotNum":"171708944076",
    "FIELD3":"Astyanax",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00280",
    "LotNum":"171708944076",
    "FIELD3":"Ultima: Quest of the Avatar",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"Working",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00281",
    "LotNum":"171708944076",
    "FIELD3":"Infiltrator",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Very Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  },
  {
    "InventoryNum":"G-NES00282",
    "LotNum":"171708944076",
    "FIELD3":"Milon's Secret Castle",
    "FIELD4":"Name OK",
    "FIELD5":"For Sale",
    "FIELD6":"None",
    "FIELD7":"Yes",
    "FIELD8":"Yes",
    "FIELD9":"N/A",
    "FIELD10":"Yes",
    "FIELD11":"Good",
    "FIELD12":"Good",
    "FIELD13":"Good",
    "FIELD14":"",
    "FIELD15":"N/A",
    "FIELD16":"",
    "FIELD17":"N/A",
    "FIELD18":"",
    "FIELD19":"N/A",
    "FIELD20":"",
    "FIELD21":"N/A",
    "FIELD22":"No"
  }
];

var markup = "";
for (var i = 0; i<json.length ;i++) {
                    // <div class="col-sm-4 col-lg-4 col-md-4">
markup += "<div class='col-sm-4 col-lg-4 col-md-4'>";
                    //     <div class="thumbnail">
markup += "<div class='thumbnail'>";
                    //         <img src="http://placehold.it/320x150" alt="">
markup += "<img src='' alt=''>"
                    //         <div class="caption">
markup += "<div class='caption'>"
                    //             <h4 class="pull-right">$24.99</h4>
                    //             <h4><a href="#">First Product</a>
markup += "<h4><a href='#'>" + json[i].FIELD3 +" </a></h4></div></div></div>"
                    //             </h4>
                    //             <p>See more snippets like this online store item at <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>                  
                    //         </div>
                    //         <div class="ratings">
                    //             <p class="pull-right">15 reviews</p>
                    //             <p>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //                 <span class="glyphicon glyphicon-star"></span>
                    //                 <span class="glyphicon glyphicon-star"></span>
markup += "<div class=''>"  
                    //             </p>
                    //         </div>
                    //     </div>
                    // </div>
}
$('.products').append(markup);
console.log(markup);                    
