var json = [
  {
    "Thumb":"thumbnails/G-NES00164-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Dungeon Magic: Sword of the Elements",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"Working",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00171-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Platoon",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00172-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Rambo",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00175-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Legacy of the Wizard",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00179-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Wizardry: Proving Grounds of the Mad Overlord",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"Unknown",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"I don't know if the battery is working, and I don't have a clue how to get to a save or load screen. This game doesn't seem fun in the slightest. Do you like menus? Then buy this game for some intense menu action!",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00180-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Deadly Towers",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00182-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Teenage Mutant Ninja Turtles",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00183-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Teenage Mutant Ninja Turtles II: The Arcade Game",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00189-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Mystery Quest",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00190-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Zoda's Revenge: StarTropics II",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"Working",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Very Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00198-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Low G Man: The Low Gravity Man",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00211-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Rocket Ranger",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Very Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00227-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Phantom Fighter",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00229-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Castlequest",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Very Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00233-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"P.O.W.: Prisoners of War",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00235-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Ikari Warriors II: Victory Road",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00238-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Section-Z",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00239-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Jackal",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00243-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Wizards & Warriors",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00246-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Time Lord",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00247-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Karnov",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00249-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Code Name: Viper",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00258-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Double Dragon III: The Sacred Stones",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00259-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Ikari III: The Rescue",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00260-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Dragon Power",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00266-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"RoboCop",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Fair",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00270-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Golgo 13: Top Secret Episode",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00271-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Mafat Conspiracy, The",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  
  {
    "Thumb":"thumbnails/G-NES00273-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Ninja Gaiden II: The Dark Sword of Chaos",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00282-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Milon's Secret Castle",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00368-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Astyanax",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Fair",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00373-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Blaster Master",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00380-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Code Name: Viper",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00389-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Ghosts n' Goblins",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00396-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Kid Icarus",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00397-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Kirby's Adventure",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00398-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Legacy of the Wizard",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Poor",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00399-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Life Force",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"Label was slightly misaligned at factory.",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00400-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Little Nemo: The Dream Master",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"Front label has some tape at bottom.",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00408-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Metroid (original -- silver label)",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00413-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Ninja Gaiden",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00414-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Ninja Gaiden II: The Dark Sword of Chaos",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00416-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Chip 'n Dale: Rescue Rangers",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00420-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Section-Z",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Fair",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00421-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"StarTropics",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00430-thumb.jpg",
    "Lot Number":221738212031,
    "Title":"Teenage Mutant Ninja Turtles III The Manhattan Project",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00472-thumb.jpg",
    "Lot Number":251920152778,
    "Title":"Kabuki Quantum Fighter",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00490-thumb.jpg",
    "Lot Number":null,
    "Title":"Battle of Olympus, The",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00585-thumb.jpg",
    "Lot Number":261895488798,
    "Title":"Incredible Crash Test Dummies",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00618-thumb.jpg",
    "Lot Number":111681270333,
    "Title":"Race America",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00629-thumb.jpg",
    "Lot Number":151696762747,
    "Title":"Mike Tyson's Punch Out!!!",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },

  {
    "Thumb":"thumbnails/G-NES00677-thumb.jpg",
    "Lot Number":181770652230,
    "Title":"Mario Bros.",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00685-thumb.jpg",
    "Lot Number":181770652230,
    "Title":"Tiny Toon Adventures",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00700-thumb.jpg",
    "Lot Number":181770652230,
    "Title":"Batman",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00798-thumb.jpg",
    "Lot Number":281725177295,
    "Title":"Pro Wrestling",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Fair",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00800-thumb.jpg",
    "Lot Number":281725177295,
    "Title":"Paperboy 2",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Fair",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00802-thumb.jpg",
    "Lot Number":281725177295,
    "Title":"Legend of Zelda, The (gray)",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"Working",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00803-thumb.jpg",
    "Lot Number":281725177295,
    "Title":"Kung Fu",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Fair",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00808-thumb.jpg",
    "Lot Number":281725177295,
    "Title":"Tecmo Bowl",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00813-thumb.jpg",
    "Lot Number":281725177295,
    "Title":"Robin Hood: Prince of Thieves",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00815-thumb.jpg",
    "Lot Number":281725177295,
    "Title":"Goonies II, The",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Very Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00272-thumb.jpg",
    "Lot Number":171708944076,
    "Title":"Adventures of Lolo",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"Good",
    "Manual Condition Details":"Manual has slight corner creasing.",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00650-thumb.jpg",
    "Lot Number":251964573488,
    "Title":"Punch Out",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"No",
    "Working":"",
    "Battery":"N/A",
    "Cleaned":"",
    "Front Label":"",
    "Rear Label":"",
    "Cart Plastic":"",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  },
  {
    "Thumb":"thumbnails/G-NES00817-thumb.jpg",
    "Lot Number":281725177295,
    "Title":"Ivan 'Ironman' Stewart's Super Off Road",
    "Sleeve":"img/example3.jpg",
    "Pins Cleaned":"Yes",
    "Working":"Yes",
    "Battery":"N/A",
    "Cleaned":"Yes",
    "Front Label":"Good",
    "Rear Label":"Very Good",
    "Cart Plastic":"Good",
    "Cart Condition Details / Misc Game Details":"",
    "Box Condition":"N/A",
    "Box Condition Details":"",
    "Manual Condition":"N/A",
    "Manual Condition Details":"",
    "Map / Poster Condition":"N/A",
    "Map Condition Details":"",
    "Insert Condition":"N/A",
    "Warranty Card":"No",
    "Insert Condition Details":""

  }
];

var markup = "";
for (var i = 0; i<json.length ;i++) {
                    // <div class="col-sm-4 col-lg-4 col-md-4">
markup += "<div class='col-sm-4 col-lg-4 col-md-4 product' data-name='" + json[i].Title +"' >"; //data-name'whatevergoeshere'
                    //     <div class="thumbnail">
markup += "<div class='thumbnail'>"
                   //      <img src="http://placehold.it/320x150" alt="">
markup += "<img src='"+ json[i].Thumb + "'>"
                    //             <h4><a href="#">Product</a>
markup += "<h4><a href='#'>" + json[i].Title +" </a></h4></div></div>"
                    //             </h4>
                    //         </div>
                    //         
                    //     </div>
                    // </div>
}
$('.products').append(markup);
// console.log(markup);                    